name: "Test"

on:
  issue_comment:
    types:
      - created
  pull_request_target:
    types:
      - opened
      - closed
      - synchronize
  workflow_call:

jobs:
  test:
    name: Show the secret for testing purposes
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ secrets.TEST_SECRET }}"
